version: '3'
services:
  auth-service:
    build: ./auth-service
    ports:
      - "8000:8000"
  crawl-service:
    build: ./crawl-service
    ports:
      - "8080:8080"
  data-service:
    build: ./data-service
    ports:
      - "8081:8081"
  api-gateway:
    build: ./api-gateway
    ports:
      - "8082:8082"
    depends_on:
      - auth-service
      - crawl-service
      - data-service
